// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpbxKKwadKRyy-LnhYhtM74eepYctSBU',
    appId: '1:33366975385:android:409c48accdd41f7f2a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    databaseURL: 'https://flutter-firebase-basics-bb333-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-basics-bb333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8E43nRPnoWgr54hgZQHReMQxj2kVbpKs',
    appId: '1:33366975385:ios:bd94a63636cdd4e52a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    databaseURL: 'https://flutter-firebase-basics-bb333-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-basics-bb333.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );
}
